# Generated by Django 3.2.8 on 2021-10-27 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='delivery_option',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='typeofrestaurant',
            name='type_of_restaurant',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
