# Generated by Django 3.2.8 on 2022-01-11 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_alter_restaurant_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='post_code',
            new_name='postcode',
        ),
    ]
