# Generated by Django 3.2.8 on 2022-02-01 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_rename_post_code_address_postcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.delivery'),
        ),
    ]
